### ISSUE TITLE
Could not find module "collection.json" while executing ng add

### ISSUE THREAD

**Issue by ngdevelop-tech** [ngx-builders/netlify-builder#25]
**Describe the bug**
I have tried to add @netlify-builder/deploy using `ng add @netlify-builder/deploy`, but it gives following error 

`An unhandled exception occurred: Could not find module "collection.json"`

This are the error logs

`[error] Error: Could not find module "collection.json" from "[project_path]\\node_modules\\@netlify-builder\\deploy".
    at Object.resolve ([project_path]\node_modules\@angular-devkit\core\node\resolve.js:151:11)
    at NodeModulesEngineHost._resolvePath ([project_path]\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:52:25)
    at NodeModulesEngineHost._resolveCollectionPath ([project_path]\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:78:35)
    at NodeModulesEngineHost.createCollectionDescription ([project_path]\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:115:27)
    at SchematicEngine._createCollectionDescription ([project_path]\node_modules\@angular-devkit\schematics\src\engine\engine.js:147:40)
    at SchematicEngine.createCollection ([project_path]\node_modules\@angular-devkit\schematics\src\engine\engine.js:140:43)
    at AddCommand.getCollection ([project_path]\node_modules\@angular\cli\models\schematic-command.js:128:35)
    at AddCommand.runSchematic ([project_path]\node_modules\@angular\cli\models\schematic-command.js:291:50)
    at AddCommand.executeSchematic ([project_path]\node_modules\@angular\cli\commands\add-impl.js:148:31)
    at AddCommand.run ([project_path]\node_modules\@angular\cli\commands\add-impl.js:45:25)
    at AddCommand.validateAndRun ([project_path]\node_modules\@angular\cli\models\command.js:134:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)`

I have looked into the @netlify-builder/deploy code, as per code `collection.json` is part of main @netlify-builder folder while it is searching `collection.json` in deploy folder.

**To Reproduce**
Execute `ng add @netlify-builder/deploy`
**Expected behavior**
should install the dependencies and add configuration in `angular.json`

**Comment by santoshyadav198613** [comment]
Hi @ngdevelop-tech ,
Thanks for reporting it.

**Comment by ngdevelop-tech** [comment]
@santoshyadav198613 This issue occurred in `windows` platform. I missed to add platform in above details.

**Comment by santoshyadav198613** [comment]
Fixed via https://github.com/ngx-builders/netlify-builder/pull/26 @ngdevelop-tech  can you verify with 1.0.6 version.

**Comment by santoshyadav198613** [comment]
Received confirmation it work now, closing this.
